import { useEffect, useState } from "react";
import { ArrowUpRight, CalendarDays, ChevronRight, CreditCard, FileText, IdCard, Mail, MapPin, Menu, Phone, ShieldCheck, Wifi, X, Zap } from "lucide-react";

const phone = "2348027052030";
const nav = ["Home", "Services", "About", "Contact"];
const clusters = [
  { key: "digital", title: "Digital & Tech", icon: Wifi, image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=85", intro: "Build, connect and protect the systems your business depends on.", detail: "We set up business websites, hosting, office networks and biometric systems. We also supply computers and accessories, then support the practical work that keeps them useful.", turnaround: "Most support requests: same day. Websites and network work: scoped after a short consultation.", services: ["Website design & hosting", "Office networking", "Biometric solutions", "Computer sales & repairs"] },
  { key: "registration", title: "Registration & Compliance", icon: FileText, image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=85", intro: "Get the documents that make a business official, without the queue.", detail: "Bring the details; we guide the process and keep you updated. We handle CAC company registration, NIN support, TIN, tax-related documentation, affidavits and online account maintenance.", turnaround: "Timelines depend on the issuing agency. We confirm requirements and expected timing before we start.", services: ["CAC registration", "NIN & TIN support", "Tax documentation", "Affidavits & online maintenance"] },
  { key: "bills", title: "Bills & Utilities", icon: CreditCard, image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=85", intro: "Pay everyday bills and business expenses quickly, at one desk.", detail: "Use NIKoncept for DSTV, PHCN, GOTV and STARTIMES payments, airline ticketing, bulk SMS and outsourced administrative support.", turnaround: "Payments are processed while you wait once your account details are confirmed.", services: ["Cable & electricity bills", "Airline ticketing", "Bulk SMS", "Outsourcing support"] },
  { key: "print", title: "Print & Branding", icon: IdCard, image: "https://images.unsplash.com/photo-1502472584811-0a2f2feb8968?auto=format&fit=crop&w=1200&q=85", intro: "Give your business a physical identity people can recognise and keep.", detail: "From plastic ID cards and name tags to large-format branding, LED displays, monograms, merchandise and promotional gifts, we produce practical brand materials for teams and campaigns.", turnaround: "Simple print jobs can be ready quickly; branded and bulk work is quoted with a production date.", services: ["Plastic ID cards & tags", "Branding & monograms", "Digital press & LED", "Merchandise & gift items"] },
  { key: "events", title: "Events & Services", icon: CalendarDays, image: "https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1200&q=85", intro: "Plan the details, then have a team there to make the day work.", detail: "We support event management, photo frames, ICT training, consulting and the supply of first-aid kits. Tell us the occasion, scale and date, and we will propose a clear plan.", turnaround: "Availability is confirmed around your date. Book early for full event coordination.", services: ["Event management", "Photo frames", "ICT training", "Consulting & first-aid kits"] }
];

function NodeNetwork() { const pts = [[55,62],[230,42],[408,110],[128,204],[320,228],[474,59],[215,282],[42,246]]; const edges = [[0,1],[1,2],[1,3],[2,4],[3,4],[3,6],[4,5],[6,7],[0,7],[4,6]]; return <svg className="network" viewBox="0 0 520 320" aria-hidden="true">{edges.map(([a,b],i)=><line key={i} x1={pts[a][0]} y1={pts[a][1]} x2={pts[b][0]} y2={pts[b][1]} style={{animationDelay:`${i*70}ms`}}/>)}{pts.map(([x,y],i)=><circle key={i} cx={x} cy={y} r={i===3?7:4.5} style={{animationDelay:`${280+i*60}ms`}}/>)}</svg> }

export default function App() {
  const [menu, setMenu] = useState(false); const [selected, setSelected] = useState(null); const [active, setActive] = useState("home");
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(e => e.isIntersecting && setActive(e.target.id)), { rootMargin: "-42% 0px -50% 0px" }); ["home","services","about","contact"].forEach(id => { const el=document.getElementById(id); if(el) observer.observe(el); }); return () => observer.disconnect(); }, []);
  useEffect(() => { const close = e => e.key === "Escape" && setSelected(null); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  const go = label => { setMenu(false); document.getElementById(label.toLowerCase())?.scrollIntoView({behavior:"smooth"}); };
  const message = "Hello NIKoncept, I would like to make an enquiry.";
  return <><a className="skip" href="#main">Skip to content</a><nav className="nav" aria-label="Main navigation"><button className="logo" onClick={()=>go("Home")} aria-label="NIKoncept home">nik<span>oncept</span></button><div className="links">{nav.map(x=><button key={x} className={active===x.toLowerCase()?"on":""} onClick={()=>go(x)}>{x}</button>)}</div><button className="talk" onClick={()=>go("Contact")}>Talk to us <ArrowUpRight size={16}/></button><button className="menu" aria-expanded={menu} aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>{menu&&<div className="mobile">{nav.map(x=><button key={x} onClick={()=>go(x)}>{x}</button>)}</div>}
  <main id="main"><header id="home" className="hero"><div><p className="eyebrow">MUSHIN, LAGOS STATE</p><h1>One partner for every system <i>and</i> every errand your business runs on.</h1><p className="lede">NIKoncept connects the technical work with the paperwork and logistics that keep a business legal and running. Professionalism anchored on integrity, RC 2478738.</p><div className="actions"><button className="primary" onClick={()=>go("Services")}>Explore services <ArrowUpRight size={16}/></button><button className="secondary" onClick={()=>go("Contact")}>Get in touch</button></div></div><NodeNetwork/></header>
  <section className="stats" aria-label="NIKoncept at a glance"><div><strong>25+</strong><span>services under one roof</span></div><div><strong>RC 2478738</strong><span>registered business</span></div><div><strong>Mushin</strong><span>Lagos State base</span></div></section>
  <section id="services" className="section"><p className="eyebrow orange">WHAT WE HANDLE</p><h2>Five clusters, one desk.</h2><p className="section-lede">From your first registration to launch-day logistics, we connect the jobs that are usually spread across several vendors.</p><div className="clusters">{clusters.map(c=>{const Icon=c.icon; return <article className="cluster" key={c.key}><img src={c.image} alt="" loading="lazy"/><div><div className="cluster-title"><span><Icon size={20}/></span><h3>{c.title}</h3></div><p>{c.intro}</p><div className="tags">{c.services.map(s=><span key={s}>{s}</span>)}</div><button className="text-button" onClick={()=>setSelected(c)}>View service details <ChevronRight size={16}/></button></div></article>})}</div></section>
  <section id="about" className="section about"><div><p className="eyebrow orange">WHO WE ARE</p><h2>Started as an ICT outfit. Grew into a front desk for small-business Lagos.</h2><p>NIKoncept began with networking, computer sales and web design. The registration, bill-payment and event requests followed because clients needed those too—and trusted the same desk to get them right.</p><p>Under Comrade Ayansanya Olaniyi (“Delaw”), Principal Partner, NIKoncept is registered under RC 2478738 and operates on a simple principle: professionalism anchored on integrity.</p><div className="principles"><div><ShieldCheck/><span><b>Registered, not informal</b>CAC-registered and accountable in every client engagement.</span></div><div><Zap/><span><b>One desk, fewer handoffs</b>Technical, administrative and logistical work handled together.</span></div></div></div><img src="https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1000&q=85" alt="Colleagues collaborating at a desk" loading="lazy"/></section>
  <section id="contact" className="section contact"><p className="eyebrow orange">REACH US</p><h2>Tell us what you need handled.</h2><div className="contact-grid"><address><p><MapPin/> <span><small>ADDRESS</small>30 Agoro Street, By Cardoso Bus Stop, Mushin, Lagos State, Nigeria</span></p><p><Phone/> <span><small>PHONE</small><a href="tel:+2348027052030">+234 802 705 2030</a><br/><a href="tel:+2348130286712">+234 813 028 6712</a></span></p><p><Mail/> <span><small>EMAIL</small><a href="mailto:info@nikoncept.com.ng">info@nikoncept.com.ng</a></span></p></address><div className="enquiry"><h3>Start on WhatsApp</h3><p>Send a short brief and the team can confirm requirements, price and timing.</p><a className="primary" href={`https://wa.me/${phone}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer">Message on WhatsApp <ArrowUpRight size={16}/></a></div></div></section></main><footer>NIKoncept · RC 2478738 · Professionalism Anchored on Integrity</footer>
  {selected&&<div className="overlay" role="presentation" onMouseDown={()=>setSelected(null)}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="Close details"><X/></button><p className="eyebrow orange">{selected.title}</p><h2 id="dialog-title">A clear scope before we start.</h2><p>{selected.detail}</p><h3>Typical requests</h3><ul>{selected.services.map(x=><li key={x}>{x}</li>)}</ul><p className="turnaround"><b>Timing:</b> {selected.turnaround}</p><a className="primary" href={`https://wa.me/${phone}?text=${encodeURIComponent(`Hello NIKoncept, I need help with ${selected.title}.`)}`} target="_blank" rel="noreferrer">Ask for a quote <ArrowUpRight size={16}/></a></section></div>}</>;
}
